spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to snncd loans related local Prod APIs "
  contactDetails:
    name: "Jorch - PROD"
    email: "Jorch@snncd.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345